### ISSUE TITLE
Blockchain reset after service gets stopped in CF

### ISSUE THREAD

**Issue by greg2git** [SAP-samples/btp-blockchain-theta#3]
i'm not sure if there's a setting somewhere to make the privatenet blockchain survive the CF service shutdown, which i think happens at least once a day on BTP. 
resetting the count or the block height defeats the goal of immutability and is not desirable. losing the balance transfers, however phantom they are, in the accounts, defeats the whole purpose of the solution.  

or did i miss the intention of this sample code?

**Comment by greg2git** [comment]
hello btp-blockchain-theta,
it's been a month, any updates?
thx, gm

**Comment by andrewlunde** [comment]
Running the blockchain on CloudFoundry is only useful for testing purposes.  If you want your testnet node to survive restarts then you need to deploy it using Kyma(Kubernetes) with an option to have a dedicated file system block.  While I know this can be done, I haven't worked out the details yet myself.  Hopefully I can do that at some point and get back with an update.

If you really want to participate in the mainnet, you should consider setting up a guardian node on your own hardware.

https://github.com/thetatoken/guardian-mainnet-guide/blob/master/docs/CLI.md#running-a-guardian-node-through-command-line


-Andrew

**Comment by greg2git** [comment]
Hi Andrew,

i understand even if i'm not happy with this approach. hence, no need to keep this issue open.

thx,
greg
